apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-mediawiki-app-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-mediawiki-app
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-mediawiki-app
    spec:
      containers:
        - name: {{ .Release.Name }}-mediawiki-app-container
          image: {{ .Values.mediawikiApp.image.repository }}:{{ .Values.mediawikiApp.image.tag }}
          imagePullPolicy: {{ .Values.mediawikiApp.image.pullPolicy }}
          ports:
            - containerPort: 80
          env:
            - name: MEDIAWIKI_DB_TYPE
              value: "mysql"
            - name: MEDIAWIKI_DB_HOST
              value: "db"
            - name: MEDIAWIKI_DB_NAME
              value: "mediawiki"
            - name: MEDIAWIKI_DB_USER
              value: "wikiuser"
            - name: MEDIAWIKI_DB_PASSWORD
              value: "secret"

