apiVersion: apps/v1
kind: Deployment
metadata:
  name: mediawiki-app-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: mediawiki-app
  template:
    metadata:
      labels:
        app: mediawiki-app
    spec:
      containers:
        - name: mediawiki-app-container
          image: {{ .Values.mediawikiApp.image.repository }}:{{ .Values.mediawikiApp.image.tag }}
          imagePullPolicy: {{ .Values.mediawikiApp.image.pullPolicy }}
          ports:
            - containerPort: 80
          env:
            - name: MEDIAWIKI_DB_TYPE
              valueFrom:
                secretKeyRef:
                  name: mediawiki-db-type-secret
                  key: mediawiki-db-type
            - name: MEDIAWIKI_DB_HOST
              valueFrom:
                secretKeyRef:
                  name: mediawiki-db-host-secret
                  key: mediawiki-db-host
            - name: MEDIAWIKI_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: mediawiki-db-name-secret
                  key: mediawiki-db-name
            - name: MEDIAWIKI_DB_USER
              valueFrom:
                secretKeyRef:
                  name: mediawiki-db-user-secret
                  key: mediawiki-db-user
            - name: MEDIAWIKI_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mediawiki-db-password-secret
                  key: mediawiki-db-password
